# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

project ‘./Holland.xcodeproj'

target 'Holland' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Holland
  pod 'SwiftyJSON'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end
